language: generic
#When we use docker, we need sudo command
sudo: required

#we need a copy of docker ready to go
services:
  - docker

before_install:
  - docker build -t averybadtime -f Dockerfile.dev .

script:
  - docker run -e CI=true averybadtime npm run test


  - docker run -e CI=true USERNAME/docker-react npm run test
